services:
  nuts-node:
    image: nutsfoundation/nuts-node:master
    ports:
      - "8081:8081"
      - "8080:8080"
    volumes:
      - ./deploy/discovery:/opt/nuts/discovery:ro
    environment:
      NUTS_CRYPTO_STORAGE: fs
      NUTS_HTTP_INTERNAL_ADDRESS: :8081
      NUTS_URL: https://nuts.nl
      NUTS_DISCOVERY_DEFINITIONS_DIRECTORY: /opt/nuts/discovery
#  nuts-admin:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      NUTS_NODE_ADDRESS: http://nuts-node:1323
