version: '3'
services:
  nuts-node:
    image: nutsfoundation/nuts-node:master
    ports:
      - "1323:1323"
      - "8443:8443"
    volumes:
      - ./data:/opt/nuts/data
      - ./deploy/node.config.yaml:/nuts.yaml
      - ./deploy/discovery:/opt/nuts/discovery:ro
      - "./deploy/certificate-and-key.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "./deploy/truststore.pem:/opt/nuts/truststore.pem:ro"
      # did:web resolver uses the OS CA bundle, but e2e tests use a self-signed CA which can be found in truststore.pem
      # So we need to mount that file to the OS CA bundle location, otherwise did:web resolving will fail due to untrusted certs.
      - "./deploy/truststore.pem:/etc/ssl/certs/Nuts_RootCA.pem:ro"
      #- "../../tls-certs/truststore.pem:/etc/ssl/certs/truststore.pem:ro"
#  nuts-admin:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      NUTS_NODE_ADDRESS: http://nuts-node:1323
