openapi: 3.0.0
info:
  title: Nuts Admin API
  version: 1.0.0

paths:
  /api/id:
    get:
      operationId: getIdentities
      responses:
        '200':
          description: List of identities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Identity"
    post:
      operationId: createIdentity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
      responses:
        '200':
          description: The identity was successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Identity"
        '400':
          description: The identity could not be created
  /api/id/{did}:
    get:
      operationId: getIdentity
      parameters:
        - name: did
          in: path
          required: true
          content:
            text/plain:
              schema:
                type: string
      responses:
        '200':
          description: The identity was successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IdentityDetails"
        '404':
          description: The identity could not be found
  /api/issuer/vc:
    parameters:
      - name: credentialTypes
        description: A comma-separated list of credential types which are returned.
        in: query
        required: true
        schema:
          type: string
    get:
      operationId: getIssuedCredentials
      responses:
        '200':
          description: List of issued VCs
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    IdentityDetails:
      type: object
      description: An identity object with additional details
      required:
        - did
        - name
        - discovery_services
        - wallet_credentials
      properties:
        did:
          type: string
        name:
          type: string
        discovery_services:
          type: array
          items:
            type: object
            required:
              - id
              - active
            properties:
              id:
                type: string
              active:
                type: boolean
              vp:
                type: object
        wallet_credentials:
          type: array
          items:
            type: object
    Identity:
      type: object
      description: An identity object
      required:
        - did
        - subject
      properties:
        did:
          description: The DID associated with this identity
          type: array
          items:
            type: string
          example:
            [did:web:example.com:iam:user1, did:tdw:1234]
        subject:
          type: string
          description: |
            Identifier the Nuts node uses to refer to this identity.
          example: "hospital_x"
